### ISSUE TITLE
(No audio) or (failed) shows up when clicking the Listen button 

### ISSUE THREAD

**Issue by loulis2** [Doublevil/Houhou-SRS#16]
the default URL stopped working probably after using cc cleaner, don't really know what happened (nothing appears on the log) I tried using alternative languagepod101 URLs, uninstalling, but nothing seems to be working

**Comment by Doublevil** [comment]
After testing it on my side, every word I try says "no audio". I guess languagepod101 changed/removed/protected their audio resources. I'll look into it some more when I have more time.

**Comment by loulis2** [comment]
its works fine now, probably something wrong with languagepod101
