### ISSUE TITLE
Feature: Set default review period

### ISSUE THREAD

**Issue by morgenman** [Doublevil/Houhou-SRS#35]
It would be very useful to set the 4h automatic time period to immediately. This would allow you to add and then study immediately. There is no point in having time _before_ you are initially exposed to the word.

**Comment by pino** [comment]
@morgenman you can already do this by changing the levels.xml file in YOUR_HOUHOU_SETTINGS_FOLDER\SrsLevels\Default. Change D1 level delayh from 4 to 0. If you don't know the path to your settings folder, you can see it by opening houhou and going to settings then scrolling all the way down.

**Comment by morgenman** [comment]
Thanks, I actually realized this recently. I had to completely remove and re-add all my vocabulary, since they were using the old values even after clearing due date and all that. It's a bit weird, but happy with this timing:

![image](https://user-images.githubusercontent.com/3505950/126099320-92a0539a-9d34-4f16-bcf0-4f4fcb59d7df.png)
