### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by hammeron-art** [Doublevil/Houhou-SRS#7]
Hello, I'm trying to build with VS 2015 after following the "Compiling the solution (for developers)" but I get this error:
```
Error	CS1061	'TrayWindow' does not contain a definition for 'Tray' and no extension method 'Tray' accepting a first argument of type 'TrayWindow' could be found (are you missing a using directive or an assembly reference?)	~\Kanji.Interface\Business\TrayBusiness.cs	90	Active
```
Is something missing in the setup?

**Comment by Doublevil** [comment]
Hello,
Are you sure you are compiling the project NotifyIconWpf (in the solution) properly? Try to compile that project alone first. Does the build on this project alone succeed? Is the reference from Kanji.Interface to NotifyIconWpf not broken?
In any case, have you tried cleaning and rebuilding?

**Comment by hammeron-art** [comment]
I managed to build it.
The Tray error for some reason goes away when I build, close and then reopen the solution.

However I had to reinstall SharpVectors, Extended.Wpf.Toolkit (installation seemed incomplete on its folders) and remove Microsoft.Speech reference to be able to build.

**Comment by Doublevil** [comment]
Okay thank you for your report.
